services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ybyra-casting-web
    restart: unless-stopped
    ports:
      - "15593:80"
    networks:
      - cloudflared
    depends_on:
      - ghost
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  ghost:
    image: ghost:5-alpine
    container_name: ybyra-casting-ghost
    restart: unless-stopped
    ports:
      - "15594:2368"
    environment:
      url: ${GHOST_URL}
      privacy__useUpdateCheck: false
      privacy__useGravatar: false
      privacy__useRpcPing: false
      use__Tls: true
    volumes:
      - ./data/ghost_content:/var/lib/ghost/content
      - ./aiven-ca.crt:/etc/ssl/certs/aiven-ca.crt:ro
      - ./config.production.json:/var/lib/ghost/config.production.json:ro
    networks:
      - cloudflared

  # mysql: (Serviço local desativado - usando Aiven Cloud)
# mysql:
#   image: mariadb:10.11
#   container_name: ybyra-casting-mysql
#   restart: unless-stopped
#   environment:
#     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#     MYSQL_DATABASE: ${GHOST_DB_NAME}
#     MYSQL_USER: ${GHOST_DB_USER}
#     MYSQL_PASSWORD: ${GHOST_DB_PASSWORD}
#   volumes:
#     - ./data/mysql:/var/lib/mysql
#     - ./mysql/init:/docker-entrypoint-initdb.d:ro
#   networks:
#     - cloudflared
#   command: --default-authentication-plugin=mysql_native_password

networks:
  cloudflared:
    external: true
