services:
  web:
    build: .
    container_name: ybyra-casting-web
    restart: unless-stopped
    networks:
      - cloudflared

  ghost:
    image: ghost:5-alpine
    container_name: ybyra-casting-ghost
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      url: ${GHOST_URL}
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      privacy__useUpdateCheck: false
      privacy__useGravatar: false
      privacy__useRpcPing: false
    volumes:
      - ./data/ghost_content:/var/lib/ghost/content
      - ./aiven-ca.crt:/etc/ssl/certs/aiven-ca.crt:ro
      - ./config.production.json:/var/lib/ghost/config.production.json:ro
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true
